services:
  kurrentdb:
    image: kurrentplatform/kurrentdb:25.0.1-x64-8.0-bookworm-slim
    environment:
      KURRENTDB_CLUSTER_SIZE: 1
      KURRENTDB_RUN_PROJECTIONS: 'All'
      KURRENTDB_START_STANDARD_PROJECTIONS: 'true'
      KURRENTDB_NODE_PORT: 2113
      KURRENTDB_INSECURE: 'true'
      KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
    ports:
      - '34605:2113'
    volumes:
      - type: volume
        source: kurrentdb-volume-data
        target: /var/lib/kurrentdb
      - type: volume
        source: kurrentdb-volume-logs
        target: /var/log/kurrentdb

volumes:
  kurrentdb-volume-data:
  kurrentdb-volume-logs:
