#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build_pkgroll() {
  set -x
  rm -rf dist
  mkdir dist
  # https://esbuild.github.io/api/#target
  npx pkgroll --target=es2020
  cp -f README.md dist
  cat package.json | jq '.main = "./index.cjs"' |
    jq '.module = "./index.mjs"' |
    jq '.types = "./index.d.ts"' |
    jq '.exports.".".import = "./index.mjs"' |
    jq '.exports.".".require = "./index.cjs"' \
      >dist/package.json
  set +x
}

build_tsup() {
  set -x
  rm -rfv dist
  tsup src/index.ts --format cjs,esm --target es2020 --no-sourcemap --cjsInterop --keep-names
  mv dist/index.js dist/index.cjs
  tsup src/index.ts --dts-only
  cp -fv README.md dist

  cat package.json | jq '.main = "./index.cjs"' |
    jq '.module = "./index.mjs"' |
    jq '.types = "./index.d.ts"' |
    jq '.exports.".".import = "./index.mjs"' |
    jq '.exports.".".require = "./index.cjs"' \
      >dist/package.json
  set +x
}

"$@"
