#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

buildMicrobundle6() {
  set -x
  if [ -n "$1" ]; then
    pushd $1
  fi
  rm -rfv dist
  npx dts-bundle-generator --no-banner --no-check --project tsconfig.json -o dist/index.d.ts src/index.ts
  npx microbundle -i src/index.ts --tsconfig tsconfig.json --no-generateTypes --no-sourcemap --no-compress --no-pkg-main --target node -f esm -o dist || true
  name=$(cat package.json | jq -r '.name')
  cp -v package.json dist
  cp -v ../../README.md dist
  cd dist
  mv index.d.ts "$name.d.ts"
  mv "$name.js" "$name.mjs"
  root=$(cat ../../../package.json | jq '{license,repository,bugs,homepage,keywords}')
  cat ../package.json \
    | jq 'del(.scripts, .exports)' \
    | jq --argjson root "$root" '. * $root' \
    | jq --arg name "$name" '
    .module = "./\($name).mjs" |
    .types = "./\($name).d.ts"
  ' > package.json
  cd ..
  if [ -n "$1" ]; then
    popd
  fi
  set +x
}

"$@"
