/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class DbxClient {
  constructor(options?: ClientOptions | undefined | null)
  /** Establish a TCP connection to the EventDBX control socket. */
  connect(): Promise<void>
  /** Close the underlying socket, if connected. */
  disconnect(): Promise<void>
  /** Returns `true` if a socket connection is currently held. */
  isConnected(): Promise<boolean>
  /** Returns the configured endpoint (host/port). */
  get endpoint(): ClientEndpoint
  /** List aggregates, optionally restricting to a specific aggregate type. */
  list(aggregateType?: string | undefined | null, options?: PageOptions | undefined | null): Promise<PageResult>
  /** Fetch a single aggregate snapshot. */
  get(aggregateType: string, aggregateId: string): Promise<any | null>
  /** Select a subset of fields from an aggregate snapshot. */
  select(aggregateType: string, aggregateId: string, fields: Array<string>): Promise<any | null>
  /** List events for an aggregate. */
  events(aggregateType: string, aggregateId: string, options?: PageOptions | undefined | null): Promise<PageResult>
  /** Append a new event with an arbitrary JSON payload. */
  apply(aggregateType: string, aggregateId: string, eventType: string, options?: AppendOptions | undefined | null): Promise<any>
  /** Create an aggregate and emit its initial event. */
  create(aggregateType: string, aggregateId: string, eventType: string, options?: CreateAggregateOptions | undefined | null): Promise<any>
  /** Archive an aggregate. */
  archive(aggregateType: string, aggregateId: string, options?: SetArchiveOptions | undefined | null): Promise<any>
  /** Restore an archived aggregate. */
  restore(aggregateType: string, aggregateId: string, options?: SetArchiveOptions | undefined | null): Promise<any>
  /** Apply a JSON Patch to the aggregate. Returns the updated snapshot. */
  patch(aggregateType: string, aggregateId: string, eventType: string, operations: JsonPatch[], options?: PatchOptions | undefined | null): Promise<any>
  /** Create a snapshot for the provided aggregate. */
  createSnapshot(aggregateType: string, aggregateId: string, options?: CreateSnapshotOptions | undefined | null): Promise<any>
  /** List snapshots with optional aggregate filters. */
  snapshots(options?: ListSnapshotsOptions | undefined | null): Promise<Array<any>>
  /** Fetch a snapshot by identifier. */
  getSnapshot(snapshotId: bigint | number, options?: GetSnapshotOptions | undefined | null): Promise<any | null>
}

export interface AppendOptions {
  payload?: JsonValue
  metadata?: JsonValue
  note?: string
  token?: string
  publishTargets?: Array<PublishTargetOptions>
}

export interface ClientEndpoint {
  ip: string
  port: number
}

export interface ClientOptions {
  ip?: string
  port?: number
  token?: string
  tenantId?: string
  noNoise?: boolean
  verbose?: boolean
  retry?: RetryOptions
}

export interface CreateAggregateOptions {
  token?: string
  payload?: JsonValue
  metadata?: JsonValue
  note?: string
  publishTargets?: Array<PublishTargetOptions>
}

export declare function createClient(options?: ClientOptions | undefined | null): DbxClient

export interface CreateSnapshotOptions {
  token?: string
  comment?: string
}

export interface GetSnapshotOptions {
  token?: string
}

export type JsonPatch =
  JsonPatchAddReplaceTest | JsonPatchRemove | JsonPatchMoveCopy

export interface JsonPatchAddReplaceTest {
  op: 'add' | 'replace' | 'test'
  path: string
  value: JsonValue
}

export interface JsonPatchMoveCopy {
  op: 'move' | 'copy'
  from: string
  path: string
}

export interface JsonPatchRemove {
  op: 'remove'
  path: string
}

export type JsonValue =
  any

export interface ListSnapshotsOptions {
  aggregateType?: string
  aggregateId?: string
  version?: bigint | number
  token?: string
}

export interface PageOptions {
  cursor?: string
  take?: number
  includeArchived?: boolean
  archivedOnly?: boolean
  token?: string
  filter?: string
  sort?: string
}

export interface PageResult {
  items: Array<JsonValue>
  nextCursor?: string
}

export interface PatchOptions {
  metadata?: JsonValue
  note?: string
  token?: string
  publishTargets?: Array<PublishTargetOptions>
}

export declare const enum PayloadMode {
  All = 'all',
  EventOnly = 'event-only',
  StateOnly = 'state-only',
  SchemaOnly = 'schema-only',
  EventAndSchema = 'event-and-schema',
  ExtensionsOnly = 'extensions-only'
}

export declare const enum Priority {
  High = 'high',
  Normal = 'normal',
  Low = 'low'
}

export interface PublishTargetOptions {
  plugin: string
  mode?: PayloadMode
  priority?: Priority
}

export interface RetryOptions {
  attempts?: number
  initialDelayMs?: number
  maxDelayMs?: number
}

export interface SetArchiveOptions {
  token?: string
  note?: string
  comment?: string
}
