export const EVENT_TRANSFORMERS = 'EVENT_TRANSFORMERS';
export const AGGREGATE_EVENT_HANDLERS = 'AGGREGATE_EVENT_HANDLERS';
export const CQRX_OPTIONS = 'CQRX_OPTIONS';
export { NO_STREAM, STREAM_EXISTS, ANY } from '@eventstore/db-client';
