export const EVENTSTORE = 'EVENTSTORE';
export const EVENT_TRANSFORMERS = 'EVENT_TRANSFORMERS';
export const AGGREGATE_ROOT_HANDLERS = 'AGGREGATE_ROOT_HANDLERS';
export const CQRX_OPTIONS = 'CQRX_OPTIONS';
