name: Continuous Integration
on:
  - push
  - pull_request

jobs:
  build:
    name: 'Test, build, release'
    runs-on: ubuntu-latest
    concurrency:
      group: ci
      cancel-in-progress: true
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 'Setup node'
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Lint source'
        run: npm run eslint

      - name: 'Type check'
        run: npm run typecheck

      - name: 'Build'
        run: npm run build

      - name: 'Check docker compose version'
        run: docker compose version

      - name: 'Start containers'
        run: docker compose up -d --quiet-pull --wait --remove-orphans

      - name: 'Setup env'
        run: |
          EVENTDBX_TOKEN=$(docker compose exec -T eventdbx dbx token bootstrap --stdout)
          echo "EVENTDBX_TOKEN=$EVENTDBX_TOKEN" >> $GITHUB_ENV

      - name: 'Test run'
        env:
          EVENTDBX_TOKEN: ${{ env.EVENTDBX_TOKEN }}
        run: npm run test:r

      - name: 'Stop containers'
        if: always()
        run: docker compose down

      - name: 'Release'
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next')
        shell: bash
        run: |
          bash Taskfile release libs/cqrx-core
          bash Taskfile release libs/kurrentdb-cqrx
          # bash Taskfile release libs/eventdbx-cqrx # TODO: Waiting fix https://github.com/eventdbx/eventdbx/issues/130
          bash Taskfile release libs/nestjs-cqrx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
